### ISSUE TITLE
Plugin page does not exist

### ISSUE THREAD

**Issue by msegzda** [ttopholm/homebridge-nordpool#8]
Homebridge plugin "home page" icon is pointing to wrong address of this plugin:

https://github.com/ttopholm/homebridge-nordpoolgit#readme
should be 
https://github.com/ttopholm/homebridge-nordpool#readme

![image](https://github.com/ttopholm/homebridge-nordpool/assets/130873/fa5c033c-8033-4c6d-8e4b-d9a9eaad206b)

**Comment by ttopholm** [comment]
WIll be fixed in the next release
